### ISSUE TITLE
Concurrent map writes in GetHandler()

### ISSUE THREAD

**Issue by debfx** [rueian/pgbroker#3]
Server.Spawn() runs a goroutine for every connection which eventually calls the ClientMessageHandlers/ServerMessageHandlers GetHandler() function.

Since the handler maps exist once per server you can end up with two goroutines updating the map `m` concurrently, crashing the application.

Given that there aren't that many message types wouldn't it be easier in general to just setup the map once in Server.Spawn()?

**Comment by rueian** [comment]
Hi @debfx,

Good idea! I will fix this today. Thanks!

**Comment by rueian** [comment]
Hi @debfx, the fix has been released in v0.0.17.

**Comment by debfx** [comment]
Nice, thanks @rueian !
