### ISSUE TITLE
Dynamic PG Resolution after Handshake

### ISSUE THREAD

**Issue by CrocHold** [rueian/pgbroker#5]
Hi @rueian,

Firstly, thanks for creating this library. 
My application requires the proxy server itself, to do the 3-way handshake with the client. And after that handshake, the proxy server should communicate with an external agent to resolve the address of the db instance in a pg server.

Can this library help?

**Comment by rueian** [comment]
Hi @CrocHold,

Yes, I think it can. There is an example of a custom `PGResolver` that creates postgres instance from a disk snapshot when a client connects to it.

Here is where the custom `PGResolver` is provided to a proxy.
https://github.com/rueian/godemand-example/blob/66fa4c7fcb2d3cffa2d1fb94948d96a43f550bb8/pgproxy/broker.go#L48

Here is the resolver implementation that asks for an external HTTP server where the database is:
https://github.com/rueian/godemand-example/blob/66fa4c7fcb2d3cffa2d1fb94948d96a43f550bb8/pgproxy/resolver.go#L24

Here is the external HTTP server that creates postgres instances from snapshots on the fly:
https://github.com/rueian/godemand-example/blob/66fa4c7fcb2d3cffa2d1fb94948d96a43f550bb8/pgplugin/controller.go#L84-L358

**Comment by CrocHold** [comment]
A custom `PGResolver` would be functioning after startup message right, & would only be able to use information available in that.
Like I stated, I require to perform the entire handshake b/w proxy and client, i.e., after reading startup: create and send authentication request message (say MD5), and obtain the hashed password from the client as a response. Only after receiving this information, my proxy server would be able to resolve the exact db by calling the external agent.

Seems like pgbroker concurrently starts processing of client side and server side messages, right after processing/ rewriting the startup. I might need to complete handshake after startup, resolve db, & then maybe then I can use the same library? I've found the subsequent messages [format](https://www.postgresql.org/docs/current/protocol-message-formats.html) in handshake as well as [implementation](https://pkg.go.dev/github.com/cybergarage/go-postgresql/postgresql/protocol/message#NewAuthenticationMD5Password). I'm afraid if making these changes would work or break something in your code. Could you please help/ check if all seems fine?

**Comment by rueian** [comment]
> Seems like pgbroker concurrently starts processing of client side and server side messages, right after processing/ rewriting the startup.

Correct. If you need more information to resolve a db, then you can put additional `rb.ReadMessage()` calls right after this line:
https://github.com/rueian/pgbroker/blob/583e3162a6bdba3a33b518d3bb16b31428efd9bc/proxy/server.go#L143

**Comment by CrocHold** [comment]
Cool, thanks!

**Comment by CrocHold** [comment]
> > Seems like pgbroker concurrently starts processing of client side and server side messages, right after processing/ rewriting the startup.
> 
> Correct. If you need more information to resolve a db, then you can put additional `rb.ReadMessage()` calls right after this line:
> 
> https://github.com/rueian/pgbroker/blob/583e3162a6bdba3a33b518d3bb16b31428efd9bc/proxy/server.go#L143

Hey @rueian, 
I did exactly that and tried to read message using rb.ReadMessage(). When I try to read message by adding this line, the entire thing comes to a hault & Dbeaver keeps waiting. 
These are the 2 functions I was thinking of using to complete handshake. `sendMessage` works fine, but `useMessage` gets into unending wait at `ReadMessage`.

```go
func (s *Server) sendMessage(ctx *Ctx, ms []byte, w io.Writer, hg MessageHandlerRegister) (err error) {
    wb := bufio.NewWriter(w)
    if handler := hg.GetHandler(ms[0]); handler != nil {
        var msg message.Reader
        if msg, err = handler(ctx, ms[5:]); err == nil {
            _, err = io.Copy(wb, msg.Reader())
        }
    } else {
        _, err = io.Copy(wb, bytes.NewReader(ms))
    }
    if err != nil {
        return err
    }
    wb.Flush()
    return nil
}
```
```go
func (s *Server) useMessage(ctx *Ctx, r io.Reader, hg MessageHandlerRegister) (err error) {
	rb := newMsgBuffer(r, 4096)
	var ms []byte
	ms, err = rb.ReadMessage()
	if err != nil {
		fmt.Println(err)
		return err
	}
	if handler := hg.GetHandler(ms[0]); handler != nil {
		_, err = handler(ctx, ms[5:])
	}
	if err != nil {
		return err
	}
	return nil

}
```

Motive was to achieve 2 seperate handshakes, like this:
write AuthMD5message to client, read passwordMessage -- subpart of handshake 1
send rewritten startup to server, read AuthMD5message, send passwordMessage -- subpart of handshake 2
AuthenticationOK msg will be the first proxy message, marking complete of both handshakes simultaneously.
After these exchanges, start the `processMessages` loops - with AuthenticationOK message getting exchanged first.

**Comment by rueian** [comment]
Hi @CrocHold, sorry about the incorrect `rb.ReadMessage()` instruction. The PostgreSQL server should send an authentication request to the client first. And by the way, the default authentication method now is SASL which is far more complex than the md5 password method.

I would suggest you first observe the messages between the server and client during the handshake with some tools, such as Wireshark, or the following self-made proxy:

```go
package main

import (
	"fmt"
	"net"
	"os"
	"os/signal"
	"syscall"

	"github.com/rueian/pgbroker/backend"
	"github.com/rueian/pgbroker/message"
	"github.com/rueian/pgbroker/proxy"
)

func main() {
	clientMessageHandlers := proxy.NewClientMessageHandlers()
	serverMessageHandlers := proxy.NewServerMessageHandlers()
	serverMessageHandlers.AddHandleAuthenticationSASL(func(ms *proxy.Ctx, msg *message.AuthenticationSASL) (*message.AuthenticationSASL, error) {
		fmt.Println("AuthenticationSASL", msg)
		return msg, nil
	})
	serverMessageHandlers.AddHandleAuthenticationSASLContinue(func(ms *proxy.Ctx, msg *message.AuthenticationSASLContinue) (*message.AuthenticationSASLContinue, error) {
		fmt.Println("AuthenticationSASLContinue", msg)
		return msg, nil
	})
	serverMessageHandlers.AddHandleAuthenticationSASLFinal(func(ms *proxy.Ctx, msg *message.AuthenticationSASLFinal) (*message.AuthenticationSASLFinal, error) {
		fmt.Println("AuthenticationSASLFinal", msg)
		return msg, nil
	})
	serverMessageHandlers.AddHandleAuthenticationOk(func(ms *proxy.Ctx, msg *message.AuthenticationOk) (*message.AuthenticationOk, error) {
		fmt.Println("AuthenticationOk", msg)
		return msg, nil
	})
	clientMessageHandlers.AddHandleSASLInitialResponse(func(md *proxy.Ctx, msg *message.SASLInitialResponse) (*message.SASLInitialResponse, error) {
		fmt.Println("SASLInitialResponse", msg)
		return msg, nil
	})
	clientMessageHandlers.AddHandleSASLResponse(func(md *proxy.Ctx, msg *message.SASLResponse) (*message.SASLResponse, error) {
		fmt.Println("SASLResponse", msg)
		return msg, nil
	})

	server := proxy.Server{
		PGResolver:            backend.NewStaticPGResolver("127.0.0.1:5433"),
		ConnInfoStore:         backend.NewInMemoryConnInfoStore(),
		ClientMessageHandlers: clientMessageHandlers,
		ServerMessageHandlers: serverMessageHandlers,
	}

	ln, err := net.Listen("tcp", ":5432")
	if err != nil {
		panic(err)
	}

	go server.Serve(ln)

	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
	<-sigs
	server.Shutdown()
}
```

**Comment by CrocHold** [comment]
Hey @rueian, sorry for the delay in response (had exams).
Right, I see. 
Yes, the SASL part was indeed the issue, thanks for the suggestion. 
pgbroker is working fine! Closing this issue now

**Comment by CrocHold** [comment]
Hi @rueian, facing a strange issue can you look at it please?

In the example written [here](https://www.postgresql.org/docs/current/sasl-authentication.html), AuthenticationOK should immediately follow after server-final-message, which is nothing but AuthenticationSASLFinal message.

This works out perfectly fine, when I send messages using dbeaver. 
However, when I act as a client using pgbroker & use my custom SASL handshake logic:
```go	
        clientSHA, err := scram.SHA256.NewClient("user-test", "password", "")

	conv := clientSHA.NewConversation()
	
	var serverMsg string
	firstMsg, err := conv.Step(serverMsg)

	s.useMessage(ctx, server, s.ServerMessageHandlers) 
	
	s.sendMessage(ctx, createSASLInitialResponseMessage("SCRAM-SHA-256", firstMsg), server, s.ClientMessageHandlers)
	
	s.useMessage(ctx, server, s.ServerMessageHandlers) 	
	
	secondMsg, err := conv.Step(ctx.ServerNextMessage)
	s.sendMessage(ctx, createSASLResponseMessage(secondMsg), server, s.ClientMessageHandlers)

	s.useMessage(ctx, server, s.ServerMessageHandlers) // SASL Final message received
	s.useMessage(ctx, server, s.ServerMessageHandlers) // AuthenticationOK message not received - infinite wait
```
connection times out, and upon checking the server never sends the AuthenticationOK message, **although it did send every other message including AuthenticationSASLFinal - which indicates Scram auth was successful.** 
(I used this [this](https://github.com/xdg-go/scram) repo for scram conversation)
(useMessage & sendMessage functions are just variants of processMessages functions)

I found [this](https://github.com/encoredev/encore/tree/2cbaa8ede69ca0edec98be5ffcc5885c86aa35b3/pkg/pgproxy),
Seems to me I'm doing the right thing, but for some reason, not able to receive/ read the AuthenticationOK message using pgbroker. Which doesn't make sense, given I'm getting the SASLFinal message with server verifier as data.
